# Generated by Django 5.0.2 on 2026-01-01 22:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(default='778-238-3371', max_length=20)),
                ('email', models.EmailField(default='info@lwsoc.com', max_length=254)),
                ('address', models.TextField(blank=True, help_text='Company address or description')),
                ('description', models.TextField(blank=True, help_text='Additional information about the company')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Information',
                'verbose_name_plural': 'Company Information',
            },
        ),
        migrations.CreateModel(
            name='UserDeletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, help_text='Optional reason for deletion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_record', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Deletion',
                'verbose_name_plural': 'User Deletions',
                'ordering': ['-deleted_at'],
            },
        ),
    ]
