# Generated by Django 5.0.2 on 2026-01-10 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the blog post', max_length=200)),
                ('slug', models.SlugField(help_text="URL-friendly version of the title (e.g., 'my-first-post')", max_length=200, unique=True)),
                ('author', models.CharField(default='Fitness Club', help_text='Author name', max_length=100)),
                ('content', models.TextField(help_text='Main content of the blog post. You can use HTML formatting.')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary/excerpt (optional, up to 500 characters)', max_length=500)),
                ('featured_image', models.ImageField(blank=True, help_text='Featured image for the blog post (optional)', null=True, upload_to='blog_images/')),
                ('is_published', models.BooleanField(default=False, help_text="Check to publish this post. Unpublished posts won't be visible to visitors.")),
                ('published_date', models.DateTimeField(blank=True, help_text='Publication date. Leave blank to use current date when published.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-published_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MembershipPlanContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='Membership Plans', help_text='Main title shown on the membership page', max_length=200)),
                ('intro_text', models.TextField(default="Join our fitness club! Choose a membership plan that fits your needs. You'll need to sign in to subscribe.", help_text='Introduction text shown at the top of the membership page')),
                ('basic_plan_name', models.CharField(default='Facility Only', help_text='Name of the basic membership plan', max_length=100)),
                ('basic_plan_description', models.TextField(default='Unlimited access to fitness facility and gym equipment.', help_text='Description of what the basic plan includes')),
                ('basic_plan_details', models.TextField(default='Great for members who want to train independently.', help_text='Additional details about the basic plan')),
                ('premium_plan_name', models.CharField(default='Facility + Classes', help_text='Name of the premium membership plan', max_length=100)),
                ('premium_plan_description', models.TextField(default='Unlimited access to fitness facility + all in-class training and group lessons.', help_text='Description of what the premium plan includes')),
                ('premium_plan_details', models.TextField(default='Best choice for members who want coached classes + open gym.', help_text='Additional details about the premium plan')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Plan Content',
                'verbose_name_plural': 'Membership Plan Content',
            },
        ),
    ]
