# Generated by Django 5.0.2 on 2026-01-10 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_blogpost_membershipplancontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPostImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image file', upload_to='blog_images/')),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility (optional)', max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which images are displayed (lower numbers first)')),
                ('is_main', models.BooleanField(default=False, help_text='Mark this as the main/featured image')),
                ('blog_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.blogpost')),
            ],
            options={
                'verbose_name': 'Blog Post Image',
                'verbose_name_plural': 'Blog Post Images',
                'ordering': ['display_order', 'id'],
                'indexes': [models.Index(fields=['blog_post', 'display_order'], name='core_blogpo_blog_po_9e3486_idx'), models.Index(fields=['blog_post', 'is_main'], name='core_blogpo_blog_po_93f56d_idx')],
            },
        ),
    ]
