# Generated by Django 5.0.2 on 2026-01-11 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blogpostimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipplancontent',
            name='basic_plan_description',
        ),
        migrations.RemoveField(
            model_name='membershipplancontent',
            name='basic_plan_details',
        ),
        migrations.RemoveField(
            model_name='membershipplancontent',
            name='basic_plan_name',
        ),
        migrations.RemoveField(
            model_name='membershipplancontent',
            name='premium_plan_description',
        ),
        migrations.RemoveField(
            model_name='membershipplancontent',
            name='premium_plan_details',
        ),
        migrations.RemoveField(
            model_name='membershipplancontent',
            name='premium_plan_name',
        ),
    ]
