# Generated by Django 5.0.2 on 2026-01-20 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_adminsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminsettings',
            name='show_platform_membership',
            field=models.BooleanField(default=True, help_text='Show/hide platform membership functions'),
        ),
        migrations.AddField(
            model_name='adminsettings',
            name='show_seller_membership',
            field=models.BooleanField(default=True, help_text='Show/hide seller membership functions'),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='show_membership_functions',
            field=models.BooleanField(default=True, help_text='[Deprecated] Use show_platform_membership instead'),
        ),
    ]
