# Generated by Django 5.0.2 on 2026-01-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Fitness Store', max_length=255)),
                ('logo', models.ImageField(blank=True, help_text='Company logo', null=True, upload_to='branding/')),
                ('favicon', models.ImageField(blank=True, help_text='Browser favicon (optional)', null=True, upload_to='branding/')),
                ('tagline', models.CharField(blank=True, help_text='Company tagline or slogan', max_length=255)),
                ('support_email', models.EmailField(blank=True, help_text='Support/contact email', max_length=254)),
                ('phone_number', models.CharField(blank=True, help_text='Contact phone number', max_length=50)),
                ('address', models.TextField(blank=True, help_text='Physical address')),
                ('hero_title', models.CharField(blank=True, help_text='Main hero headline (max 120 chars)', max_length=120)),
                ('hero_subtitle', models.TextField(blank=True, help_text='Hero subtitle/description (max 500 chars)', max_length=500)),
                ('hero_cta_text', models.CharField(blank=True, help_text="Call-to-action button text (e.g., 'Get Started')", max_length=50)),
                ('hero_cta_url', models.CharField(blank=True, help_text="CTA button URL or Django URL name (e.g., 'membership_plans')", max_length=255)),
                ('hero_image', models.ImageField(blank=True, help_text='Hero section background image', null=True, upload_to='hero/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company Settings',
                'verbose_name_plural': 'Company Settings',
            },
        ),
    ]
