# Generated by Django 5.0.2 on 2026-01-24 09:24

from django.db import migrations


def create_default_settings(apps, schema_editor):
    """Create default CompanySettings instance"""
    CompanySettings = apps.get_model('company_settings', 'CompanySettings')
    if not CompanySettings.objects.exists():
        CompanySettings.objects.create(
            company_name="Fitness Store",
            tagline="Your path to a healthier you",
            hero_title="Transform Your Fitness Journey",
            hero_subtitle="Join our community of fitness enthusiasts. Access premium workouts, expert guidance, and achieve your goals.",
            hero_cta_text="Get Started",
            hero_cta_url="members:membership_plans",
        )


def reverse_default_settings(apps, schema_editor):
    """Remove default settings on migration rollback"""
    CompanySettings = apps.get_model('company_settings', 'CompanySettings')
    CompanySettings.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_settings, reverse_default_settings),
    ]
