# Generated by Django 5.0.2 on 2026-01-24 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0002_auto_20260124_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='pickup_only',
            field=models.BooleanField(default=False, help_text='If enabled, only pickup orders are allowed. Shipping address will be hidden and only the first pickup location will be shown.'),
        ),
    ]
