# Generated by Django 5.0.2 on 2026-01-24 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_settings', '0003_companysettings_pickup_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='companysettings',
            name='shipping_policy',
            field=models.TextField(blank=True, help_text='Shipping policy text displayed on cart page. Leave blank to hide.'),
        ),
    ]
