# Generated by Django 5.0.2 on 2026-01-19 01:42

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_add_status_and_business_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='commission_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.10'), help_text='Platform commission rate (e.g., 0.10 = 10%)', max_digits=5),
        ),
    ]
