# Generated by Django 5.0.2 on 2026-01-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_alter_seller_commission_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='payout_hold_days',
            field=models.PositiveIntegerField(default=7, help_text='Number of days to hold earnings before they become available for payout (default: 7 days)'),
        ),
    ]
