# Generated by Django 5.0.2 on 2026-01-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0004_seller_payout_hold_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='is_trusted',
            field=models.BooleanField(default=False, help_text='Trusted sellers may have additional permissions (e.g., auto-refund)'),
        ),
        migrations.AddField(
            model_name='seller',
            name='stripe_account_id',
            field=models.CharField(blank=True, help_text='Stripe Connect account ID', max_length=255, null=True),
        ),
    ]
