# Generated by Django 5.0.2 on 2026-01-20 07:12

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0005_seller_is_trusted_seller_stripe_account_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerMembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Plan name (e.g., 'Basic', 'Premium', 'VIP')", max_length=200)),
                ('slug', models.SlugField(help_text="URL-friendly identifier (e.g., 'basic', 'premium', 'vip')")),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly price (use 0.00 for free plans)', max_digits=10)),
                ('description', models.TextField(help_text='Brief description. HTML supported: &lt;p&gt;, &lt;ul&gt;, &lt;li&gt;, &lt;strong&gt;, etc.')),
                ('details', models.TextField(blank=True, default='', help_text='Additional details (optional). HTML supported: &lt;ul&gt;&lt;li&gt; for lists, &lt;p&gt; for paragraphs.')),
                ('is_active', models.BooleanField(default=True, help_text='Only active plans are shown to customers')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which plans appear (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(help_text='Seller who owns this membership plan', on_delete=django.db.models.deletion.CASCADE, related_name='membership_plans', to='sellers.seller')),
            ],
            options={
                'verbose_name': 'Seller Membership Plan',
                'verbose_name_plural': 'Seller Membership Plans',
                'ordering': ['display_order', 'name'],
                'unique_together': {('seller', 'slug')},
            },
        ),
    ]
