# Generated by Django 5.0.2 on 2026-01-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0006_sellermembershipplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='membership_intro_text',
            field=models.TextField(blank=True, default='Choose a seller membership plan that fits your needs.', help_text='Introduction text shown at the top of your membership plans page'),
        ),
    ]
