# Generated by Django 5.0.2 on 2026-01-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0007_seller_membership_intro_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellermembershipplan',
            name='is_approved',
            field=models.BooleanField(default=False, help_text='Admin approval required. Only approved plans are shown publicly and in navigation.'),
        ),
    ]
