"""
Django settings for fitness_club project.
Generated by 'django-admin startproject' using Django 5.0.2.
"""

from pathlib import Path
import os

# ------------------------------------------------------------
# Paths
# ------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent.parent  # points to /fitness_club (outer) then Root

# ------------------------------------------------------------
# Core settings
# ------------------------------------------------------------
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY", "dev-only-change-me")
DEBUG = os.environ.get("DJANGO_DEBUG", "1") == "1"

ALLOWED_HOSTS = ["127.0.0.1", "localhost"]

# Replit support (safe locally)
replit_domains = os.environ.get("REPLIT_DOMAINS")
if replit_domains:
    domain_list = [d.strip() for d in replit_domains.split(",") if d.strip()]
    ALLOWED_HOSTS += domain_list
    CSRF_TRUSTED_ORIGINS = [f"https://{d}" for d in domain_list]
else:
    CSRF_TRUSTED_ORIGINS = []

# ------------------------------------------------------------
# Applications
# ------------------------------------------------------------
INSTALLED_APPS = [
    # Django core
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sites",  # required for allauth

    # Third-party
    "rest_framework",
    "allauth",
    "allauth.account",
    "allauth.socialaccount",

    # Your apps
    "members.apps.MembersConfig",
    "api",
    "accounts",
    "products",
    "cart",
    "orders",
    "payment.apps.PaymentConfig",
]

# ------------------------------------------------------------
# Middleware
# ------------------------------------------------------------
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",

    "allauth.account.middleware.AccountMiddleware",  # ✅ required by django-allauth

    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

print("MIDDLEWARE FINAL:", MIDDLEWARE)




# ------------------------------------------------------------
# URLs / WSGI / ASGI  ✅ IMPORTANT: must match the project package name
# ------------------------------------------------------------
ROOT_URLCONF = "fitness_club.fitness_club.urls"
WSGI_APPLICATION = "fitness_club.fitness_club.wsgi.application"
ASGI_APPLICATION = "fitness_club.fitness_club.asgi.application"


# ------------------------------------------------------------
# Templates
# ------------------------------------------------------------
TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR/ "templates"], # if you use a global /templates folder, put BASE_DIR / "templates" here
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",  # REQUIRED for allauth
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

# ------------------------------------------------------------
# Database
# ------------------------------------------------------------
# If you're using PostgreSQL, keep this.
# If not ready, you can temporarily switch to sqlite3.

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": "fitness_club_db",
        "USER": "fitness_user",
        "PASSWORD": "Fitness123!",   # move to env later
        "HOST": "localhost",
        "PORT": "5432",
    }
}

# ------------------------------------------------------------
# Auth / Users
# ------------------------------------------------------------


AUTHENTICATION_BACKENDS = [
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
]

SITE_ID = 1

# Allauth email-only login
ACCOUNT_AUTHENTICATION_METHOD = "email"
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = "mandatory"  # require email verification
ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION = True

# Redirects
LOGIN_URL = "/accounts/login/"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"

# ------------------------------------------------------------
# Password validation
# ------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]

# ------------------------------------------------------------
# Internationalization
# ------------------------------------------------------------
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True

# ------------------------------------------------------------
# Static / Media
# ------------------------------------------------------------
STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# ------------------------------------------------------------
# Email (DEV)
# ------------------------------------------------------------
EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "Fitness Club <no-reply@fitnessclub.test>"

# For local email dev signup
#Keep both configs, switch by environment

DEBUG = os.getenv("DEBUG", "True") == "True"

if DEBUG:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    ACCOUNT_EMAIL_VERIFICATION = "none"
    ACCOUNT_EMAIL_REQUIRED = False
else:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    ACCOUNT_EMAIL_VERIFICATION = "mandatory"
    ACCOUNT_EMAIL_REQUIRED = True



