# Generated by Django 5.0.2 on 2026-01-06 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_orderitem_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Location name (e.g., 'Main Store', 'Downtown Branch')", max_length=200)),
                ('address1', models.CharField(help_text='Street address', max_length=255)),
                ('address2', models.CharField(blank=True, default='', help_text='Apartment, suite, etc. (optional)', max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('province', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('country', models.CharField(default='Canada', max_length=100)),
                ('phone', models.CharField(blank=True, default='', help_text='Contact phone for this location', max_length=30)),
                ('instructions', models.TextField(blank=True, default='', help_text="Special instructions for customers (e.g., 'Pick up at front desk', 'Hours: Mon-Fri 9am-5pm')")),
                ('is_active', models.BooleanField(default=True, help_text='Only active locations are shown to customers')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which locations appear (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Pickup Location',
                'verbose_name_plural': 'Pickup Locations',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='is_pickup',
            field=models.BooleanField(default=False, help_text='If True, customer selected pickup instead of shipping'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_location',
            field=models.ForeignKey(blank=True, help_text='Selected pickup location (only set if is_pickup=True)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='orders.pickuplocation'),
        ),
    ]
