# Generated by Django 5.0.2 on 2026-01-18 06:01

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_pickuplocation_order_is_pickup_order_pickup_location'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='line_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Total for this line item (price * quantity)', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Platform commission fee', max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Seller who owns this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='sellers.seller'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='seller_earnings',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Amount seller earns after commission', max_digits=10),
        ),
    ]
