# Generated by Django 5.0.2 on 2026-01-18 06:32

from django.db import migrations, models


def set_empty_payment_intent_ids_to_none(apps, schema_editor):
    """Convert empty strings to None before adding unique constraint"""
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(payment_intent_id='').update(payment_intent_id=None)


def reverse_set_empty_payment_intent_ids_to_none(apps, schema_editor):
    """Reverse: convert None to empty strings (not needed, but for completeness)"""
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(payment_intent_id__isnull=True).update(payment_intent_id='')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_orderitem_line_total_orderitem_platform_fee_and_more'),
    ]

    operations = [
        # Step 1: Add field as nullable, non-unique first
        migrations.AddField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(blank=True, default='', help_text='Stripe payment intent ID or other payment gateway ID (unique to prevent double-charging)', max_length=255, null=True),
        ),
        # Step 2: Convert empty strings to None (None values are not considered equal for uniqueness)
        migrations.RunPython(set_empty_payment_intent_ids_to_none, reverse_set_empty_payment_intent_ids_to_none),
        # Step 3: Add unique constraint (NULL values are allowed, but duplicates of actual values are not)
        migrations.AlterField(
            model_name='order',
            name='payment_intent_id',
            field=models.CharField(blank=True, default='', help_text='Stripe payment intent ID or other payment gateway ID (unique to prevent double-charging)', max_length=255, null=True, unique=True),
        ),
    ]
