# Generated by Django 5.0.2 on 2026-01-19 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_add_payment_intent_id'),
        ('sellers', '0005_seller_is_trusted_seller_stripe_account_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded'), ('partially_refunded', 'Partially Refunded'), ('disputed', 'Disputed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Refund amount (in CAD)', max_digits=10)),
                ('reason', models.CharField(blank=True, help_text='Reason for refund', max_length=255, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='requested', help_text='Current refund status', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stripe_refund_id', models.CharField(blank=True, help_text='Stripe refund ID after processing', max_length=255, null=True)),
                ('created_by', models.ForeignKey(help_text='User who initiated the refund', on_delete=django.db.models.deletion.PROTECT, related_name='refunds_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(help_text='Order being refunded', on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='orders.order')),
                ('order_item', models.ForeignKey(blank=True, help_text='Specific order item being refunded (null for full order refunds)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='orders.orderitem')),
                ('seller', models.ForeignKey(help_text='Seller who owns the product being refunded', on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='sellers.seller')),
            ],
            options={
                'verbose_name': 'Refund',
                'verbose_name_plural': 'Refunds',
                'ordering': ['-created_at'],
            },
        ),
    ]
