# Generated by Django 5.0.2 on 2025-12-09 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_product_name_alter_product_price_productaudio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='charge_gst',
            field=models.BooleanField(default=True, verbose_name='Charge GST (5%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='charge_pst',
            field=models.BooleanField(default=False, verbose_name='Charge PST (7%)'),
        ),
        migrations.AddField(
            model_name='product',
            name='quantity_in_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Available quantity'),
        ),
    ]
