# Generated by Django 5.0.2 on 2026-01-10 23:58

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_remove_product_category_remove_order_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembershipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Plan name (e.g., 'Basic', 'Premium', 'VIP')", max_length=200)),
                ('slug', models.SlugField(help_text="URL-friendly identifier (e.g., 'basic', 'premium', 'vip')", unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Monthly price (use 0.00 for free plans)', max_digits=10)),
                ('description', models.TextField(help_text='Brief description of what this plan includes')),
                ('details', models.TextField(blank=True, default='', help_text='Additional details about the plan (optional)')),
                ('is_active', models.BooleanField(default=True, help_text='Only active plans are shown to customers')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order in which plans appear (lower numbers first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Membership Plan',
                'verbose_name_plural': 'Membership Plans',
                'ordering': ['display_order', 'name'],
            },
        ),
    ]
