# Generated by Django 5.0.2 on 2026-01-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0019_alter_membershipplan_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='membership_level',
            field=models.CharField(default='none', help_text='Membership plan identifier (slug). Can be a platform plan slug or seller plan full slug (seller_X_slug)', max_length=100),
        ),
    ]
