# Generated by Django 5.0.2 on 2026-01-20 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_alter_memberprofile_membership_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='memberprofile',
            name='platform_auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='platform_is_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='platform_last_billed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='platform_membership_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='platform_membership_level',
            field=models.CharField(blank=True, help_text='Platform membership plan slug', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='platform_membership_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='platform_next_billing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='seller_auto_renew',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='seller_is_member',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='seller_last_billed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='seller_membership_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='seller_membership_level',
            field=models.CharField(blank=True, help_text='Seller membership plan full slug (seller_X_slug)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='seller_membership_started',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='memberprofile',
            name='seller_next_billing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='membership_level',
            field=models.CharField(default='none', help_text='Legacy field - use platform_membership_level or seller_membership_level instead', max_length=100),
        ),
    ]
