# Generated by Django 5.0.2 on 2026-01-21 07:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_memberprofile_platform_auto_renew_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberprofile',
            name='platform_auto_renew',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='platform_is_member',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='platform_last_billed_date',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='platform_membership_expires',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='platform_membership_level',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='platform_membership_started',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='platform_next_billing_date',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='seller_auto_renew',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='seller_is_member',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='seller_last_billed_date',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='seller_membership_expires',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='seller_membership_level',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='seller_membership_started',
        ),
        migrations.RemoveField(
            model_name='memberprofile',
            name='seller_next_billing_date',
        ),
        migrations.AlterField(
            model_name='memberprofile',
            name='membership_level',
            field=models.CharField(default='none', help_text='Membership plan identifier (slug). Can be a platform plan slug or seller plan full slug (seller_X_slug)', max_length=100),
        ),
        migrations.CreateModel(
            name='UserMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_identifier', models.CharField(help_text='Plan identifier: platform plan slug or seller plan full slug (seller_X_slug)', max_length=200)),
                ('plan_type', models.CharField(choices=[('platform', 'Platform'), ('seller', 'Seller')], help_text='Type of membership plan', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this membership is currently active')),
                ('started_at', models.DateTimeField(auto_now_add=True, help_text='When the membership started')),
                ('expires_at', models.DateTimeField(help_text='When the membership expires')),
                ('auto_renew', models.BooleanField(default=True, help_text='Whether to auto-renew this membership')),
                ('next_billing_date', models.DateField(blank=True, help_text='Date of next renewal charge', null=True)),
                ('last_billed_date', models.DateField(blank=True, help_text='Most recent billing date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who has this membership', on_delete=django.db.models.deletion.CASCADE, related_name='user_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Membership',
                'verbose_name_plural': 'User Memberships',
                'ordering': ['-started_at'],
                'indexes': [models.Index(fields=['user', 'is_active'], name='members_use_user_id_6e271f_idx'), models.Index(fields=['expires_at'], name='members_use_expires_434022_idx')],
                'unique_together': {('user', 'plan_identifier')},
            },
        ),
    ]
