# Generated by Django 5.0.2 on 2025-12-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_inventorylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorylog',
            name='change_type',
            field=models.CharField(choices=[('INITIAL', 'Beginning balance'), ('ORDER', 'Order'), ('RESTOCK', 'Restock'), ('ADJUST', 'Manual adjustment'), ('REFUND', 'Refund/Return')], max_length=20),
        ),
    ]
