# Generated by Django 5.0.2 on 2026-01-18 05:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_is_featured'),
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seller',
            field=models.ForeignKey(blank=True, help_text='Seller who owns this product', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='sellers.seller'),
        ),
    ]
